controller:
  name: controller
  image:
    repository: nginx-ingress-controller
    tag: "18.0831"

  # controller.persistentVolumeClaims -- List of persistent volume claims to create.
  # For very long comments, break them into multiple lines.
  # @default -- the chart will construct this list internally unless specified
  persistentVolumeClaims: []

  extraVolumes:
    - name: config-volume
      configMap:
        # controller.extraVolumes[0].configMap.name -- Uses the name of the configmap created by this chart
        name: nginx-ingress-config

  # controller.ingressClass -- Name of the ingress class to route through this controller
  ingressClass: nginx

  # controller.podLabels -- The labels to be applied to instances of the controller pod
  podLabels: {}

  publishService:
    # controller.publishService.enabled -- Whether to expose the ingress controller to the public world
    enabled: false

  # controller.replicas -- (int) Number of nginx-ingress pods to load balance between
  replicas:

  service:
    annotations:
      # controller.service.annotations."external-dns.alpha.kubernetes.io/hostname" -- Hostname to be assigned to the ELB for the service
      external-dns.alpha.kubernetes.io/hostname: stupidchess.jmn23.com

    type: LoadBalancer
