name: 🌟 Feature Request
description: Suggest an idea for this project
title: "[Feat]: <title>"
labels:
  - "enhancement"
  - "triage"
assignees:
  - "nholuongut"
  - "Nepo26"
body:
  - type: markdown
    attributes:
      value: "Thank you for the interest in the project! :blush:"
  - type: textarea
    attributes:
      label: "General Summary"
      description: "Provide a general summary of the issue in the Title above"
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Is your feature request related to a problem? Please describe and/or link to a bug issue."
      description: "A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]"
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Expected Behavior"
      description: "Tell us how it should work"
    validations:
      required: false
  - type: textarea
    attributes:
      label: "Current Behavior"
      description: "Explain the difference from current behavior"
    validations:
      required: false
  - type: textarea
    attributes:
      label: "Possible Solution"
      description: "Ideas on how to implement the addition or change"
    validations:
      required: false
  - type: textarea
    attributes:
      label: "Alternatives you've considered"
      description: "A clear and concise description of any alternative solutions or features you've considered."
    validations:
      required: false
  - type: textarea
    attributes:
      label: Further Information
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!
        
        - How has this issue affected you? What are you trying to accomplish?
        - Providing context helps us come up with a solution that is most useful in the real world
        
        _Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in._
    validations:
      required: false
